services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_admin_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://trading_user:secure_trading_password@postgres:5432/trading_db
      HF_HOME: /app/.cache/huggingface
      TRANSFORMERS_CACHE: /app/.cache/huggingface
      HUGGINGFACE_HUB_CACHE: /app/.cache/huggingface
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/workspace
      - huggingface_cache:/app/.cache/huggingface
    working_dir: /workspace
    command: sleep infinity

volumes:
  postgres_data:
  huggingface_cache: