services:
  postgres:
    image: postgres:17
    environment:
      # Admin credentials for PostgreSQL initialization
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      
      # Pass trading configuration to initialization script
      DB_TRADING_DB_NAME: ${DB_TRADING_DB_NAME}
      DB_TRADING_USER_NAME: ${DB_TRADING_USER_NAME} 
      DB_TRADING_USER_PASSWORD: ${DB_TRADING_USER_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount the initialization script to create the trading database and user
      - ./.devcontainer/scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HF_HOME: /workspace/.cache/huggingface
      HUGGINGFACE_HUB_CACHE: /workspace/.cache/huggingface
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/workspace
      - huggingface_cache:/workspace/.cache/huggingface
    working_dir: /workspace
    entrypoint: ["bash", "/workspace/scripts/entrypoint.sh"]

volumes:
  postgres_data:
  huggingface_cache: